# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Empty', max_length=50)),
                ('brand', models.CharField(default='Empty', max_length=30)),
                ('color', models.CharField(default='Empty', max_length=30)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('description', models.TextField(default='Empty')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
