# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'shoes'), ('2', 'boots')], default='1', max_length=1),
        ),
    ]
