# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20170402_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'shoes'), ('2', 'boots')], default='1', max_length=1),
        ),
    ]
