# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170318_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
